spring:
  datasource :
    url: ${SPRING_DATASOURCE_URL}
  flyway:
    enabled: true
    baselineOnMigrate: true
    baselineVersion: 1
    locations: classpath:db/migration
websiteUrl : https://fluxmart.vercel.app