spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate.connection.provider_disables_autocommit: true


    jwt:
    secretKey: ${JWT_SECRET}
    refreshExpiration: 604800
    accessExpiration: 86400

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhooksecretkey: ${STRIPE_WEBHOOK_SECRET_KEY}


websiteUrl: http://localhost:5173