spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}

  flyway:
    enabled: true                # ensures Flyway runs on startup
    locations: classpath:db/migration  # default folder for migration scripts
    baseline-on-migrate: true    # useful if you already have an existing schema
    baseline-version: 1          # version to start from
    validate-on-migrate: true    # checks applied migrations against scripts
    clean-disabled: true         # prevents accidental schema wipes
websiteUrl: https://fluxmart.vercel.app
